name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: |
          ./mvnw clean test
        env:
          MAVEN_OPTS: -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository
